# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ScootShare Backend CI
run-name: Running build for  ${{ github.sha}}
on:
  push:
    branches: [ "main" ]


jobs:
  build:
    name: Continuous Integration of main pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci    

    - name: Login to Supabase
      run: npm run login ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Link to Supabase project
      run: npm run link  ${{ secrets.SUPABASE_PROJECT_REF }}

    - name: Deploy migrations
      run: npm run deploy