# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ScootShare Backend CI Test
run-name: Running build for  ${{ github.sha}}
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Continuous Integration of main pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci    

    - name: Start Supabase
      run: npm run start

    - name: Test migrations
      run: npm run apply:migrations

    - name: Stop Supabase
      run: npm run stop